### ISSUE TITLE
Βαθμολογία εξεταστικής Φεβ 2020

### ISSUE THREAD

**Issue by epidrome** [courses-ionio/hci#1273]
Οι βαθμοί έχουν αναρτηθεί.

Στην περίπτωση που ο βαθμός σας είναι κάτω από 5, πχ. 1 ή 2, 

τότε αυτό σημαίνει ένα από τα παρακάτω

1. δεν έχετε παραδώσει καμία εργασία (κάπου το 20% της τάξης)
2. έχετε παραδώσει μόνο την εργασία με την γραμμή εντολών (κάπου το 30% της τάξης)
3. δεν έχετε στείλει τελική αναφορά ή έχετε στείλει μόνο ένα από τα παραδοτέα της υποχρεωτικής εργασίας συμμετοχικού περιεχομένου (κάπου το 10% της τάξης)

αν κάτι από αυτά δεν ισχύει και θέλετε να δείτε το γραπτό της τελικής εξέτασης τότε θα πρέπει να κανονίσετε μια συνάντηση για να δούμε μαζί στο γραφείο το γραπτό σας

**Comment by Marialena98** [comment]
Καλησπέρα, έκανα 5 από τις ασκήσεις στη γραμμή εντολών και έστειλα τελική αναφορά αλλά δεν πέρασα το μάθημα. Θα ήθελα να κανονίσουμε συνάντηση!

**Comment by epidrome** [comment]
σύμφωνα με τις οδηγίες του μαθήματος:

> Βαθμολογία: 40% Τελική εξέταση* 20% Συμμετοχικό εκπαιδευτικό υλικό*, 40% 4 ασκήσεις

> *υποχρεωτική συμπλήρωση της βάσης για να γίνει τελική βαθμολόγηση

αυτός ήταν ο βασικός λόγος που δεν πέρασε το μάθημα σχεδόν το 30% της τάξης

**Comment by p13mark1** [comment]
Καλησπέρα, ακολουθησα τις οδηγιες για απαλακτικη εργασια εκανα 6 από τις ασκήσεις στη γραμμή εντολών,2 εικονες  και 2 βιογραφιες αλλα δεν εχω περασει το μαθημα με βαθμο 2  θα ήθελα να σαςσυνάντησω!(επισης εχω παραδωσει και αλλες εργασιες στο παρελθον). Ευχαριστω

**Comment by epidrome** [comment]
@p13mark1 απάντηση στο σχετικό θέμα #1280

**Comment by epidrome** [comment]
@Marialena98 
θα πρέπει να γίνει νέο αίτημα για την εξεταστική του Σεπτεμβρίου, ώστε να γίνει βαθμολόγηση, 

ακολουθούν μερικά σχόλια (τα οποία κανονικά θα πρέπει να γίνονται μόνο στις συναντήσεις του μαθήματος):

από την αναφορά-γραπτό του Ιαν όλα ήταν (οριακά) κάτω από την βάση, με το συμμετοχικό πολύ κάτω, 

φυσικά, αναλυτική συζήτηση-αξιολόγηση μπορεί να γίνει μόνο κατά την διάρκεια του μαθήματος και όχι εδώ.. 

..και σίγουρα όχι σε email που συνεχίζεις να στέλνεις, δείχνοντας ότι αγνοείς τις οδηγίες του μαθήματος

**Comment by Marialena98** [comment]
Τι εννοείται νέο αίτημα; Με τις έξτρα εργασίες; Στη συνάντηση μας μου είχατε πει πως θα προβείτε σε αναβαθμολόγηση αν προσθέσω το συμμετοχικό υλικό το οποίο και έκανα ευθύς αμέσως και δεχτήκατε το αίτημα μου οπότε θεώρησα πως θα γίνει αλλαγή του βαθμού. Δεν γίνονται διαλέξεις γι'αυτό έψαξα εναλλακτικό τρόπο επικοινωνίας.

**Comment by epidrome** [comment]
φυσικά και έγινε αναβαθμολόγηση του Ιαν. και ο βαθμός ήταν πάλι κάτω από την βάση

> φυσικά, αναλυτική συζήτηση-αξιολόγηση μπορεί να γίνει μόνο κατά την διάρκεια του μαθήματος και όχι εδώ

**Comment by Marialena98** [comment]
Τον Ιανουάριο έδωσα το μάθημα και πήρα βαθμό 1. Κανονίσαμε συνάντηση και αφού είδατε το γραπτό μου μου είπατε να προσθέσω το συμμετοχικό υλικό και θα μου κάνετε αναβαθμολόγηση. Ο βαθμός που εμφανίζεται στο σύστημα είναι από την εξεταστική Ιανουαρίου-Φεβρουαρίου πριν τη συνάντηση.

**Comment by Marialena98** [comment]
Συνεπώς για να περάσω το μάθημα αρκεί να ολοκληρώσω τις νέες εργασίες ή πρέπει να κάνω αλλαγές και στις προηγούμενες; Ευχαριστώ.

**Comment by epidrome** [comment]
#1280
