### ISSUE TITLE
Ασκηση Α1 οδηγει σε σελιδα 404 

### ISSUE THREAD

**Issue by akontinis** [courses-ionio/hci#1311]
Καλημερα στο συμμετοχικο υλικο στο Α1 οδηγει σε σελιδα 404 
![2020-09-05 11-22-21](https://user-images.githubusercontent.com/29643887/92301339-becf0980-ef6b-11ea-8b4f-c84742ce94fd.gif)

**Comment by epidrome** [comment]
fixed, thanks!
