### ISSUE TITLE
Κωδικός τηλεδιάσκεψης

### ISSUE THREAD

**Issue by panosath** [courses-ionio/hci#1389]
Που μπορώ να βρω τον κωδικό τηλεδιάσκεψης; Ο κωδικός VLyk0t δεν λειτουργεί και δεν μπόρεσα να βρω κάποιον άλλον, ούτε μέσω των οδηγιών, ούτε μέσω αναζήτησης στις σελίδες στο github. Κάνω κάτι στραβά;

**Comment by epidrome** [comment]
σίγουρα κάνεις κάτι διαφορετικό

ίσως το μεηλ σου δεν είναι ιονιο;

σήμερα είχαμε κάπου 70 φοιτητές στο ζουμ

**Comment by panosath** [comment]
Στο zoom χρησιμοποιώ το mail μου από το ιόνιο, αλλά δεν κατάφερα να μπω στην αίθουσα.. Δεν έχω ιδέα τι μπορεί να συμβαίνει

**Comment by epidrome** [comment]
μήπως δεν μπαίνεις με το σωστό λινκ?
https://courses-ionio.github.io/help/distance/

**Comment by panosath** [comment]
Με το λινκ από τις οδηγίες μπαίνω στο μάθημα, και προσπάθησα να χρησιμοποιήσω το meeting password που ανέφερα αρχικά, αυτόν που έχετε αναρτήσει στις ανακοινώσεις, στα Issues του hci.. Ακόμα και τον κωδικό συνάντησης 78053008669 από τις οδηγίες προσπάθησα να εισάγω στο zoom και πάλι τίποτα..

**Comment by epidrome** [comment]
˚κανείς άλλος δεν έχει αυτό το πρόβλημα!

σίγουρα εμείς εδώ δεν μπορούμε να βοηθήσουμε περισσότερο

μάλλον θα πρέπει να μιλήσεις με το ζουμ, δεν μπορώ να σκεφτώ κάτι άλλο

εκπαιδευτικά πάντως ότι λέμε στο μάθημα είναι αναρτημένο

οπότε μέχρι να βρεις μια λύση μπορείς πάντα να παρακολουθείς ασύγχρονα με τα άλλα εργαλεία που έχουμε
