### ISSUE TITLE
netlify και ασκήσεις προγραμματισμού

### ISSUE THREAD

**Issue by elenberg-io** [courses-ionio/hci#1392]
Η ερωτηση μου αφορα ολες τις εργασιες: Χρειαζεται λινκ για netlify σε ολες τις ασκησεις που εχουμε κανει μεχρι τωρα; Αν oχι, σε ποιες; Εχω κανει search για keyword netlify σε ολο σας το αρχειο projects και η μονη αναφορα που υπαρχει σε netlify ειναι στο index.md στο cv directory. Ευχαριστω.

**Comment by epidrome** [comment]
@elenberg-io τώρα το είδα γιατί δεν είχες κάνει μένσιον κάποιον!

αντιγράφω από τις αντίστοιχες οδηγίες ασκήσεων προγραμματισμού:

> Για να βαθμολογηθεί μια άσκηση θα πρέπει ο λογαριασμός σας στο codepen.io να είναι ο ΑΜ σας ή το όνομα χρήστη στο Ιόνιο και **η απάντηση σας να ενσωματωθεί στην σελίδα της αντίστοιχης άσκησης της ιστοσελίδας του βιβλίου**

και από το ριντμι για την εγκατάσταση της ιστοσελίδας:

> 2. Configure the deployment from your netlify account.

επίσης το έχουμε πει προφορικά αρκετές φορές και στο μάθημα
