### ISSUE TITLE
Σχετικά με ασκήσεις γραμμής εντολών

### ISSUE THREAD

**Issue by apostoloskp** [courses-ionio/hci#1393]
Καλησπέρα, θυμάμαι πως είχατε πει πως πρέπει να κάνουμε μόνο τις ασκήσεις προγραμματισμού HCI.
Ισχύει το ίδιο και στις γραμμής εντολών? Γιατί στις 2 πρώτες έκανα από το warmup. Θα βαθμολογηθούν αυτές ή
να τις σβήσω και να τις αλλάξω σε HCI?
ή να κάνω από την επόμενη(8η εβδομάδα) από λίστα με HCI?

**Comment by epidrome** [comment]
κανόνισε ένα ντέμο στις ώρες του μαθήματος ώστε να απαντήσουμε σε όλα τα ερωτήματα
