### ISSUE TITLE
ερώτηση 

### ISSUE THREAD

**Issue by TheodoreZ-107** [courses-ionio/hci#1446]
@c15pati @epidrome 
Κύριοι θα ηθελε να κανω μια ερώτηση. Επειδή στον υπολογιστή μου , παρα τις αμέτρητες προσπάθιες μου , το Ubundu δεν ανοίγει ,θα μπορούσα να κάνω τις γραμμές εντολών απο εναν υπολογιστή ενός συμφοιτητή μου στον οποίο ανοίγει;

**Comment by epidrome** [comment]
η ιδιοκτησία του υπολογιστή δεν είναι στα κριτήρια βαθμολόγησης, 

δεν μας ενδιαφέρει αν ο υπολογιστής είναι δανεικός ή κλεμένος! :))

κοιτάζοντας λίγο το αποθετήριο σου φαίνεται πως δεν έχεις κάνει το υποχρεωτικό 1ο συμμετοχικό περιοχόμενο
https://github.com/TheodoreZ-107/hci/tree/2019107/projects/2019107

**Comment by TheodoreZ-107** [comment]
Ευχαριστώ για την απάντηση αλλα τι σημασία έχει εαν εχω κάνει το 1ο συμμεττοχικό περιεχόμενο εφόσον τώρα έχω την ευχαίρια να ασχοληθώ με τις εργασίες σας.

**Comment by TheodoreZ-107** [comment]
Επίσης, επειδή θα κάνω τις ασκησεις στον υπολογιστή του συμμαθητή μου όλες οι καταγραφές ανεβαίνουν στο δικο του προφίλ στο Asciinema.Υπάρχει κάποιο πρόβλημα σε αυτο;Εαν ναι πως μπορώ να το λύσω.

**Comment by epidrome** [comment]
1. το 1ο συμμετοχικό περιεχόμενο είναι υποχρεωτικό και δεν απαιτεί λινουξ, επομένως θα μπορούσε να είχε γίνει έγκαιρα
2. οι συγχρονοι υπολογιστές επιτρέπουν την δημιουργία ξεχωριστών λογαριασμών χρήστη, επομένως, ναι, υπάρχει πρόβλημα αν στείλειτε εργασίες από αλλού
3. το μάθημα δεν γίνεται εδώ με τσατ, αλλά στις συναντήσεις με προσωπικό ραντεβού, οπότε το θέμα εδώ κλείνει και θα πρέπει να κανονίσεις μια συνάντηση την Τρίτη ή την Τετάρτη να δούμε πως θα σε βοηθήσουμε
