### ISSUE TITLE
Απορία 

### ISSUE THREAD

**Issue by AlexandrosV20** [courses-ionio/hci#1488]
Έχω απορίες σχετικά με το συμμετοχικό περιεχόμενο και τις οδηγιες του μπορειτε να μου πειτε τι εννοειτε με αυτο " _Οι παρακάτω εργασίες βασίζονται σε αποθετήριο που περιέχει submodules, τα οποία απαιτούν την χρήση γραμμής εντολών. Μπορείτε να αποφύγετε αυτήν την τεχνολογία αν αντιγράψετε τους αντίστοιχους φακέλους, π.χ., εικόνες μέσα στο αποθετήριο σας, αλλά προφανώς η βαθμολόγηση δεν θα είναι ίδια, ειδικά στο μάθημα του λογισμικού._". Που χρησιμεύει κατι τετοιο και ποια η λογική ;

**Comment by epidrome** [comment]
https://courses-ionio.github.io/help/faq/
