### ISSUE TITLE
Απορία

### ISSUE THREAD

**Issue by p15xiar** [courses-ionio/hci#1489]
Καλησπέρα σας κύριε @epidrome 

Είχα ακολουθήσει κανονικά την διαδικασία των commit στο χειμερινό εξάμηνο του ακαδημαϊκού έτους 2020-2021 αλλά λόγω δικού μου λάθους κατά την διαδικασία του Pull request αυτό δεν έγινε αποδεκτό. Θα μπορούσα να βελτιώσω/διορθώσω την τελική αναφορά μου σε τακτά χρονικά διαστήματα, ανά εβδομάδα για παράδειγμα, και να κάνω Pull request ώστε να βαθμολογηθώ στην εξεταστική του Σεπτεμβρίου και εάν αυτό είναι δυνατό θα ανακοινωθεί προθεσμία παράδωσης; 

Ξέρω ότι υπάρχει διαφορετική βαθμολόγηση σε τέτοιες περιπτώσεις αλλά θα ήθελα εάν αυτό καταστεί δυνατό να ξεκινήσω διαδικασίες για πτυχιακή τον ερχόμενο Σεπτέμβριο.

Ευχαριστώ εκ των προτέρων
Σπυρίδων Ξιάρχος
Π2015048
p15xiar@ionio.gr

**Comment by epidrome** [comment]
https://courses-ionio.github.io/help/faq/
