### ISSUE TITLE
images for readme

### ISSUE THREAD

**Issue by p15theo3** [courses-ionio/hci#19]
![1](https://cloud.githubusercontent.com/assets/22753415/20148717/8b0084e6-a6b6-11e6-8290-733fc0b5acd5.jpg)
![2](https://cloud.githubusercontent.com/assets/22753415/20148719/8b06b712-a6b6-11e6-95c0-63c9b6042d36.jpg)
![3](https://cloud.githubusercontent.com/assets/22753415/20148720/8b0709e2-a6b6-11e6-98a6-2620f842ff53.jpg)
![4](https://cloud.githubusercontent.com/assets/22753415/20148718/8b05c672-a6b6-11e6-8b9b-4fabbb48fa6c.jpg)

**Comment by merkourisa** [comment]
Το prototype δεν ανεβαίνει εδώ διάβασε τις οδηγίες
